### ISSUE TITLE
getting "::" on gits status <projectname>

### ISSUE THREAD

**Issue by hagzag** [rafi/gits#1]
I have the following ~/.gits.yml file:

```
---
projects:
  is:
    path: ~/projects/Customers/IntelSport
    repos:
      # - dir: ansible-tutorial
      #   src:
      - dir: terra-intel-cloud
        src: git@gitlab.com:insport/terraform-samples.git
  wm:
    path: ~/projects/Customers/worldmate
    repos:
      - dir: autobots-k8s-onprem
        src: git@github.com:lightapp/la-deploy.git
  la:
    path: ~/projects/lightapp/
    desc: "lightapp Hybrid - LION automation code"
    repos:
      - dir: la-deploy
        src: git@github.com:lightapp/la-deploy.git
      - dir: la-cloud
        src: git@github.com:lightapp/la-cloud.git
  hagzag:
    desc: My dotfiles
    repos:
    - dir: ~/.config
      src: git@github.com:rafi/.config.git
    - dir: ~/.config/nvim
      src: git@github.com:rafi/vim-config.git

```
A simple gits status <project name> yields the following:

```
hagzag@🌀terra-intel-cloud 👉  gits status wm
::
hagzag@🌀terra-intel-cloud 👉  gits status la
::
hagzag@🌀terra-intel-cloud 👉  gits status is
::
hagzag@🌀terra-intel-cloud 👉  gits status hagzag
::
```
